version: "3.9"

services:
  api:

    image: $GIT_PATH:$GITHUB_REF_NAME-$GITHUB_RUN_ID
    ports:
      - 25000:25000
    environment:
      - DB_PASSWORD=$DB_PASSWORD
      - DB_USER=$DB_USER
      - DB_NAME=$DB_NAME
      - DB_HOST=postgres_db

    depends_on:
      postgres_db:
        condition: service_healthy

  postgres_db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_USER=$DB_USER
      - POSTGRES_NAME=$DB_NAME

    healthcheck:
      test: pg_isready -U $DB_USER
      timeout: 3s
      retries: 10
      interval: 3s
